export const staticSchools = [
  {
    id: 1,
    name: "SDN 001 MERDEKA KOTA BANDUNG",
    status: "Negeri",
    npsn: "20245231",
    bentuk: "SD",
    telp: "0224231251",
    alamat: "Jl. Merdeka No. 9",
    kelurahan: "Braga",
    kecamatan: "Kec. Sumur Bandung",
    lat: null,
    lng: null,
  },
  {
    id: 2,
    name: "SDN 002 KARANGMULYA KOTA BANDUNG",
    status: "Negeri",
    npsn: "20245212",
    bentuk: "SD",
    telp: "0226039074",
    alamat: "Jl. Rajawali Sakti  No. 226",
    kelurahan: "Dungus Cariang",
    kecamatan: "Kec. Andir",
    lat: null,
    lng: null,
  },
  {
    id: 3,
    name: "SD ADVENT CIMINDI",
    status: "Swasta",
    npsn: "20219531",
    bentuk: "SD",
    telp: "0226010612",
    alamat: "Jl. Raya Cimindi No. 74",
    kelurahan: "Campaka",
    kecamatan: "Kec. Andir",
    lat: null,
    lng: null,
  },
  // tambahkan sisanya sesuai datamu
];
